# Generated by Django 5.1.3 on 2025-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_course_description_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Elektron pochta manzili'),
        ),
    ]
